import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import {
  Avatar,
  ColorSchemeScript,
  MantineProvider,
  Text,
} from '@mantine/core';
import './global.css';
import '@mantine/core/styles.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <ColorSchemeScript />
      </head>
      <body
        className={inter.className}
        style={{
          width: '100%',
        }}
      >
        <MantineProvider>
          <header
            style={{
              backgroundColor: '#228BE6',
              width: '100%',
              height: '60px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              padding: '0 20px',
            }}
          >
            <Text component="p" fw="bold" size="xl" c="white">
              請求書インマイハウス
            </Text>
            <Avatar alt="it's me" color="white" />
          </header>
          <div style={{ padding: '0 20px' }}>{children}</div>
        </MantineProvider>
      </body>
    </html>
  );
}
