import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Avatar, ColorSchemeScript, MantineProvider } from '@mantine/core';
import './global.css';
import '@mantine/core/styles.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <ColorSchemeScript />
      </head>
      <body
        className={inter.className}
        style={{
          margin: '0 auto',
          padding: '0 20px',
          width: '100%',
        }}
      >
        <MantineProvider>
          <header
            style={{
              backgroundColor: '#228BE6',
              width: '100%',
              height: '40px',
              padding: '0 20px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'flex-end',
            }}
          >
            <Avatar alt="it's me" color="white" />
          </header>
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
